### ISSUE TITLE
broken links?

### ISSUE THREAD

**Issue by 1864mp** [lainy/NikonLens#2]
*  -    Protocol: http://nikonhacker.com/wiki/Lens_Serial_Interface
 *  -      Pinout: http://nikonhacker.com/wiki/F-Mount
I cannot access these pages

"Hmm. We’re having trouble finding that site."

Wonder if these sites still available if not can we have the info here?

**Comment by lainy** [comment]
Ah, looks like nikonhacker.com is down... wonder if it'll be back up at some point.
Anyway thanks for pointing this out! I've updated the links to use archived copies of the website via archive.org

**Comment by 1864mp** [comment]
Iainy thanks for those links - much appreciated.
